### ISSUE TITLE
RackHD API may not reply with all running workflows

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#1]
from Megan:

We’re using the workflows API to poll for monorail workflows. Basically, we take the list of workflows, look for the one we’re running and check it’s status to determine if it’s still pending and which tasks are pending.

We’re seeing an issue occasionally where the query will return without our workflow in the list. On our end, it causes an error and we exit from our provisioning here as this is unexpected. Manual queries later will have the workflow back in the list. 

We were wondering if this was a known issue or if this is something we can provide some logs/debug around? Or, are there any known issues with number of requests? (Maybe some tuning we can do on our side).

**Comment by heckj** [comment]
When the workflow “disappears” from the list, does it appear to come back on a further request – i.e. the request to list a workflows isn’t returning data consistently? If so, that’s definitely not a known issue and we should open up a bug on that and track that down.

**Comment by miles378** [comment]
From a sidebar with @king-jam we have seen some occasional failures recently that *may* be similar.  Tagged him here for alignment.

**Comment by meganmurawski** [comment]
We're doing a GET on nodes/<node id>/workflows and then looking for the workflow within the workflows list. We poll on this request, so the workflow is there originally. Sometimes, the workflow is not found within the list, which causes our logic to exit.

After the failure, we can typically manually query the workflows and see the workflow in the response.

**Comment by tysonmcnulty** [comment]
Adding to Megan's comment: what I've seen happen is that the GET for the workflow will occasionally come back empty, and waiting 5-10 minutes and doing the same query manually gets the right result.

**Comment by heckj** [comment]
@tysonmcnulty thanks! That's awesome detail. Any chance you noted how long that http request took to complete? 

@benbp ^^ this sounds like the messenger maybe timed out or something while retrieving the list of active workflows (timeout in the communications between on-http and on-taskgraph)

**Comment by benbp** [comment]
Yeah, sounds like a messenger timeout. Depending on the number of active workflows, this can be a LOT of data coming out of the database and over the wire, so I wouldn't be surprised if we're timing out.

I think you'll have better results if you poll `/nodes/<node id>/workflows/active`: that will give you only the workflow that's actively running for the node, and the request is less likely to time out.

**Comment by meganmurawski** [comment]
We can change the way we poll for the workflows, but I would feel better about getting an error from this query if there is a timeout instead of incomplete/inconsistent results. 

Can we be certain that querying the active workflows won't also result in a timeout?

**Comment by king-jam** [comment]
@meganmurawski there is an issue with using the GET `/nodes/<node id>/workflows/active` route since at workflow completion you will get a 204 not found which may be a problem.

I think the right solution is to take the response from POST `/nodes/<node id>/workflows` and grab the workflow id, then pass that into a poll of GET `/workflows/<workflow id>`.

If you do that then you aren't querying as much data. You can simplify your WorkflowFetcher code, and have a better control loop.

**Comment by benbp** [comment]
Agreed @meganmurawski, didn't mean to suggest this isn't a real issue. Active workflows will be much less likely to result in a timeout since the data size is limited to a single workflow, but as @king-jam said you will have issues with a 204 on completion.

@heckj @RackHD/corecommitters I think the proper fix here might be to go directly to the database from the on-http server instead of passing this large amount of data over a single AMQP message from on-taskgraph (going directly to the db will also make it easier to paginate the data, or add logic to the route for better filtering/limiting).

**Comment by meganmurawski** [comment]
@benbp @king-jam it sounds like the right solution for us will be grabbing /workflows/<workflow_id>

is there any possibility that we'll see timeouts on that resource if there are a bunch of workflows in general? or should it be ok since it's a small amount of data?

Pagination sounds like a good idea for the workflows. We can probably avoid using it for our polling, but may need to query all the workflows at some point.

**Comment by benbp** [comment]
@meganmurawski I don't think you'll see timeout issues for the `/workflows/<workflow_id>` route, partly because it's a small amount of data, and also because the logic for that route goes straight to the database rather than receiving data over AMQP (which would be the fix for the other routes). 

One caveat:
The `nodes/<id>/workflows` route also goes straight to the database, however it will return the entire workflow history, and I don't think the output is sorted in any way, so you aren't necessarily guaranteed to know which workflow is the latest one without doing a createdAt/updatedAt sort yourself (which is kind of annoying).

**Comment by heckj** [comment]
@benbp could you verify - will this be effectively resolved when the workflow refactor work merges in? 
RackHD/on-taskgraph#56, https://github.com/RackHD/on-tasks/pull/116, and RackHD/on-http#112

**Comment by benbp** [comment]
@heckj we didn't make any updates to that route with the refactor, but it would be trivial to add some code in there that sorts the output as its own item of work.

**Comment by benbp** [comment]
@heckj wasn't this resolved to be a unit test bug? Or is there still an issue on our side?

**Comment by heckj** [comment]
I never heard a full resolution, but I believe it was an mismatch in the client code using the APIs.
