### ISSUE TITLE
Docker instructions no longer work because of b2d deprecation

### ISSUE THREAD

**Issue by benbp** [RackHD/RackHD#166]
The docker instructions in `docker/README.md` are no longer functional, since they rely on boot2docker, which has now been deprecated in favor of docker toolbox.

FYI @rolandpoulter

**Comment by rolandpoulter** [comment]
https://github.com/RackHD/RackHD/pull/157 fixes this issue.

Has nothing to do with using a boot2docker.iso in fact docker toolbox is based on the same iso. See https://docs.docker.com/machine/reference/create

The issue here is that the vagrant box being uses was updated on atlas but not on github. Since I didn't specify a `box_version` it always tried to get the latest version which is currently broken for `dduportal/boot2docker`

**Comment by pscharla** [comment]
@benbp Does the above PR fix this issue? Should this be closed?

**Comment by rolandpoulter** [comment]
@pscharla yes, this bug was fixed.
