### ISSUE TITLE
Internal Error 500 on simultaneous install 

### ISSUE THREAD

**Issue by richardkirchhofer** [RackHD/RackHD#227]
Trying to install ESXi on two servers roughly simultaneously. First sever running faster gets esx-ks file from on-http and continues OK. Second server comes in a tries to retrieve sex-ks and gets 500. When I do a wget at this point of same file I see an error in upstart log saying code can't determine which node I am referring. Result is my wget also gets 500. Seems to be a problem either related to one template with different payloads running the install or some missing design. I could investigate it some more but it would be helpful if there was some detail doc on the execution of graphs and processing of templates and profiles.

**Comment by zyoung51** [comment]
@richardkirchhofer I saw a similar issue related to the node losing its identity in the database.  If you query /lookups and see that the mac/ip/node relationship for the node is missing the proper { node: nodeid } value then you may be encountering the same issue.  A fix for the issue was posted very recently: https://github.com/RackHD/on-tasks/pull/200.  If you are seeing the node value being lost, can you retry with that fix in place?

**Comment by benbp** [comment]
@richardkirchhofer yes, also note that you can't wget from a host and get a valid response back, because we do a lookup to find the nodeId based on the client IP for the http request (this is how we know what files to render down, based on the workflow). If the IP is from your host, we likely won't have a node document for that, and will return a 500.

**Comment by heckj** [comment]
believe resolved with  RackHD/on-tasks#200
