### ISSUE TITLE
[1.2] 1.1/templates/library and 1.1/profiles/library APIs are no longer showing 'contents' field

### ISSUE THREAD

**Issue by johren** [RackHD/RackHD#247]
It looks like the change that caused https://github.com/RackHD/RackHD/issues/235 somehow came into the 1.2 branch with one of these PRs.  

https://github.com/RackHD/on-taskgraph/pull/108
https://github.com/RackHD/on-tasks/pull/220

I'm not sure if 
a.  something unexpected came in and needs to be backed out
b.  the change was intended and we need the fix for this issue (https://github.com/RackHD/on-http/pull/309) also merged into this branch

**Comment by benbp** [comment]
@johren I'm suspecting this is a similar issue to what I think https://github.com/RackHD/RackHD/issues/248#issuecomment-222776296 is, in that your on-core dependency is on the master branch instead of the 1.2 branch, in 1.2 we still have a contents field in the template model: https://github.com/RackHD/on-core/blob/release/1.2.0-branch/lib/models/template.js#L21 (as opposed to master: https://github.com/RackHD/on-core/blob/master/lib/models/template.js#L17)

**Comment by johren** [comment]
Yes, confirmed that a rebuild of on-http resolved this issue.  Closing.
