### ISSUE TITLE
Rackhd HA

### ISSUE THREAD

**Issue by James-Dao** [RackHD/RackHD#298]
Hi,

If want to use it in production environment, are there some data need to be persistent. If so, how to do it?

From DaoCloud

**Comment by heckj** [comment]
@James-Dao The current default for our processes is to maintain all persistence in MongoDB. That system supports clustering, so you can maintain a clustered MongoDB instance to support RackHD if you wish. There's an ongoing thread about just this in our google groups forum at https://groups.google.com/forum/m/#!topic/rackhd/moTZRIedusQ

Do note that some of the processes within RackHD *are not* amenable to running multiple instances in an active/active configuration (dhcp-proxy being the key, along with ISC DHCP) simply because the protocol (DHCP) does't accomodate an active/active scenario. Depending on your HA architecture, you may want to use something like pacemaker or an equivalent master-election with a quorum-based underling system to be responsible for running RackHD processes to enable a fault tolerance to achieve robust availability.  There are several different options within this space that could work - it's very dependent on your environment and architecture for what you're trying to achieve.

**Comment by James-Dao** [comment]
Thanks

**Comment by leoyjchang** [comment]
Close this ticket as we questions has been answered and didn't hear concern from submitted for a long time.
