### ISSUE TITLE
Customized workflow will be lost if on-taskgraph restart

### ISSUE THREAD

**Issue by wangzhizheng** [RackHD/RackHD#438]
I customized the Graph.Discvery  to do something when discover a new node.
But I found the workflow will back to the default one if on-taskgraph is restarted.
Any way to save it persistently?

**Comment by heckj** [comment]
Morning @wangzhizheng -

The setup that RackHD uses will load and update the graphs that have been stored in code, on disk, to overwrite any in the mongodb/persistence mechanism on process start. So if you want to make permanent changes to the discovery graph, you'll need to change the code on the filesystem, not just manipulate the data through the API.

The code is located in on-taskgraph, and the default is actually a graph that run another graph:
 - https://github.com/RackHD/on-taskgraph/blob/master/lib/graphs/discovery-sku-graph.js
 - https://github.com/RackHD/on-taskgraph/blob/master/lib/graphs/discovery-graph.js

If you're running from source using the Vagrant example, these files will be in `~/src/on-taskgraph/lib/graphs/`. If you're using the debian packages we make and host on bintray, the files will be in `/var/renasar/on-taskgraph/lib/graphs/` - and if you make your own packages, you should be able to trace down where these guys are located :-)

Also worth nothing, the code that gets invoked for initial discovery on PXE boot is hard coded right now to these graph names. There's work pending (https://github.com/RackHD/RackHD/wiki/proposal-configurable-default-discovery-workflow) to make that configurable so that you can more easily keep the original discovery graph and add your own, and use your own graph as a default for PXE booting.

**Comment by wangzhizheng** [comment]
Thank you @heckj 
Let me edit it from source first

**Comment by leoyjchang** [comment]
@wangzhizheng Are you good to close this ticket per Joe's explanation?
