### ISSUE TITLE
add ability to add catalogs to nodes through RackHD API

### ISSUE THREAD

**Issue by johren** [RackHD/RackHD#48]
It would be very helpful in some testing cases to have a way to inject node catalog entries through the API.  For example, the physical or virtual environment that I have doesn't provide some catalog data, but I want to be able to test functionality or fixes against that catalog data.

**Comment by heckj** [comment]
@brianparry @yyscamper this seems highly valuable, thinking both as a southbound API and a (future authenticated) northbound API so that it's usable as an arbitrary tool upload from devices as well as a coordination data point from consumers of RackHD.

**Comment by yyscamper** [comment]
Expose POST catalog API bring both power and harm.
It's easy to test, to mimic a physical device, but we lack the means to validate user's input, and when we encounter a bug in future, the catalog data becomes not reliable, because it maybe manipulated by user.

If only for test purpose, I think we can directly touch the mongodb.
If only enable it for RackHD southbound API, seems it is duplicated, because now POST /tasks/<identifier> can do similar thing.

**Comment by brianparry** [comment]
@yyscamper I would think that we'd want to leave input validation out of it since tests may need to inject invalid data.  If the intent is to use this for test only, we could protect against using it in production with a configuration switch.

@johren I think it would be helpful if you could provide some specific test scenarios where you would use this feature so we can get a sense for the level of flexibility you'd need.

**Comment by johren** [comment]
I will gather more specific test scenarios and add them to this.

**Comment by DavidjohnBlodgett** [comment]
@johren @brianparry @yyscamper Hi guys, just wanted to follow up and and see if we should address this request, are there any specific use cases we have available? Otherwise, should I close this ticket? Thanks!

**Comment by pscharla** [comment]
Looks like @johren is on vacation for a bit. We'll need to put this one on the side until we get more specific scenarios.

**Comment by johren** [comment]
I forget the specific use case that brought this up.  Don’t have the cycles right now to dig it up and it isn't a pressing issue so I will go ahead and close it for now and reopen if it comes up again.
