### ISSUE TITLE
Create and store a new node manually is failing

### ISSUE THREAD

**Issue by manfrednde** [RackHD/RackHD#483]
Using RackHD master I am not able to create manually a new node of type management using POST node API. 

I am using the following payload to create the node:

{
  "name": "management server",
  "autoDiscover": "true",
  "obmSettings": [
            {
                "config": {
                    "host": "172.31.128.77",
                    "user": "admin",
                    "password": "admin"
                },
                "service": "ipmi-obm-service"
            }
        ],
  "type": "mgmt"
}

The node ID gets created but  I see that graph (Graph.MgmtSKU.Discovery) that should be run on the node(  "autoDiscover": "true",)
is still in pending states after more than 2 hours. 

: curl localhost:8080/api/common/workflows/be947a11-25fb-4bd1-b50b-6995adb60598 | pyth...  Wed Nov  2 21:54:52 2016

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 100  6315  100  6315    0     0   351k      0
--:--:-- --:--:-- --:--:--  362k
        "injectableName": "Graph.MgmtSKU.Discovery",
                    "injectableName": "Task.Graph.Run.Discovery",
                    "injectableName": "Task.Inline.Pollers.CreateDefault",
                    "injectableName": "Task.Graph.Run.SkuSpecific",
    "injectableName": "Graph.MgmtSKU.Discovery",
            "injectableName": "Task.Catalog.GenerateTag",
            "state": "pending",
            "injectableName": "Task.Inline.Pollers.CreateDefault",
            "state": "pending",
            "injectableName": "Task.Graph.Run.Discovery",
            "state": "pending",
            "injectableName": "Task.Catalog.GenerateSku",
            "state": "pending",
            "injectableName": "Task.Catalog.GenerateEnclosure",
            "state": "pending",
            "injectableName": "Task.Graph.Run.SkuSpecific",
            "state": "pending",
It looks like : 
(1)	The task schema specifies the wrong job, so the discovery (LLDP catalog) actually runs the wrong job. (It causes the workflow hangs)
(2)	The obm settings is not persisted in database so the catalog that bases on IPMI will fail since it cannot find the obm from database. (It causes the catalog failure

**Comment by yyscamper** [comment]
There are two sub-issue for this problem:
1 - The lldp catalog always fail since the task-schema wrongly points a wrong job. The wrong job is waiting microkernel to do catalog, since no microkernel, so the task will hang. The solution is in this PR: https://github.com/RackHD/on-tasks/pull/371

2 - ipmi catalog will always fail since it cannot find the obm setting, this is due to obm setting isn't added into database,  the solution is in this PR: https://github.com/RackHD/on-tasks/pull/371

**Comment by srinia6** [comment]
@manfrednde : Are you using 2.0 or 1.1 api? Because 2.0 does not use obmSettings anymore under node. 2.0 has obms as a seperate model, and it can be posted via /obms route or /node/id/obms    route. Example is http://rackhd.readthedocs.io/en/latest/tutorials/vagrant.html?highlight=ipmi-obm-service    and the schema for obms - for ref  https://github.com/RackHD/on-http/blob/master/static/schemas/obms/ipmi-obm-service.json  @brianparry @dalebremner please add if i might have missed something here.

**Comment by yyscamper** [comment]
@srinia6: This is to manually create a new node, so you will not know the node id in advance, that means post /obms or /node/:id/obms will not work in this situation.

**Comment by manfrednde** [comment]
I agree with Felix

**Comment by brianparry** [comment]
@yyscamper @manfrednde There is a fundamental difference from previous behavior here in that `obmSettings` is *not* a property of a node anymore.  It is now its own, resource related to a node by a one-to-many relation.  An obm cannot exist without a nodeId.  We have spoofed this behavior in the 1.1 API to maintain compatibility but the 2.0 does not support posting obms along with a node.  It is a two step process of posting a node followed by posting an obm and associating it with that node.

**Comment by brianparry** [comment]
@manfrednde Are you get a 201 response back from your POST /nodes/ request?  You should be getting a schema violation error back with the obmSettings property included with the request body.  At one point, the schema incorrectly allowed additional properties which could be the problem here if you're running older code.

**Comment by manfrednde** [comment]
@brianparry  what will happen if I set up "autoDiscover": "true" in the payload ?
does the node gets discover automatically  ?
if yes , some tasks that use the obm settings will fail

**Comment by manfrednde** [comment]
@brianparry  I am getting a 201 response back from  POST /nodes/ request

**Comment by brianparry** [comment]
@manfrednde You make a good point about `autoDiscover`.  We overlooked that when changing obms.   I'm going through @yyscamper's PR which should fix that problem.  As it is today, you should have gotten a 400 back from that requiest (https://github.com/RackHD/on-http/blob/master/static/schemas/2.0/node.2.0.json#L49).  How old is the code you're using?

**Comment by manfrednde** [comment]
@brianparry I am using OnRack 2.1 .  I should not get a 400 as "obmSettings" parameter is still defined. ( https://github.com/RackHD/on-http/blob/master/static/schemas/2.0/node.2.0.json#L21 ) even in the latest code.

**Comment by brianparry** [comment]
@manfrednde Okay, now I'm confused.  That code pre-dates our changes to the obm design and should have worked in exactly the way you expected.  The bug you've identified should only be in newer versions of code after refactoring obms.

**Comment by yyscamper** [comment]
PRs have been merged and verified pass.
