### ISSUE TITLE
add tests to on-tftp

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#49]
https://github.com/RackHD/on-tftp is really quite a light wrapper around the node-tftp library, but it could still use some tests to exercise that wrapper and some of the light logic we put around it (logging errors, and info). 

The tests within on-syslog (https://github.com/RackHD/on-syslog/tree/master/spec) makes a good baseline pattern for someone to follow if they were looking for an example...

**Comment by DavidjohnBlodgett** [comment]
@heckj I have already started working on this in my own fork https://github.com/DavidjohnBlodgett/on-tftp/tree/unitTests just a heads up, just have afew more tests to add once it's inside the request blocks... and I kinda side tracked finishing it because I started using the branch to do some exploratory testing of mocking~ I will try to post a cleaned up PR next week.

**Comment by DavidjohnBlodgett** [comment]
resolved in https://github.com/RackHD/on-tftp/pull/26
