### ISSUE TITLE
IPMI SEL LIST poller - updates to deal with clearing memory errors

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#55]
from @king-jam:

> For the IPMI poller, did you include logic in IPMI polling that handles an out of band clearing of the current SEL?
> 
> I understand that by default your poller works off asserted/deasserted sensors but in the case of a Memory Error, it will stay asserted in the log but doesn't ever deassert. The only way to clear an event vs. a sensor is clearing the log but it seems your poller still remembers the event as asserted even if it is no longer in the log.

@heckj:
> We explicitly did not, as we weren't sure what assumptions we could make about anything else using the SEL logs and didn't want to break any existing process that expected to have the SEL logs in a "just so" state by clearing them unexpected.
> That's something we can absolutely add - either as a part of the poller and a regular process, or as a separate API call.

@king-jam 
> I'm thinking you would either want to provide an API so you can control and maintain state or add something in your poller to look for:
    {{ 1 | 11/02/2014 | 21:53:48 | Event Logging Disabled #0xf6 | Log area reset/cleared | Asserted}}

> as a queue to clear out your current polling data. Seeing it unexpectedly would mean the user did an OOB clear and probably foregoes any state they intended to have. An API call would accomplish the same thing, you'd just be able to maintain any internal states you desire.

**Comment by brianparry** [comment]
@heckj This may actually be a bug rather than an enhancement.  I think the current implementation will continuously emit alerts once the first ECC error is detected in the SEL.  For now, I think the best option is to provide an API to clear the condition so upper layers like LTAE can manage the state.  Longer term, I think we need more of a stats based approach to dealing with occasional events like this.  Occasional, correctable ECC errors are normal and I don't think we should be alerting every time they happen.  I think a better approach is to track a a count of them over time and use thresholds to determine whether the error rate is something that warrants an alert.  The mechanism that ends up managing the counts could also manage deasserting ECC errors.

**Comment by heckj** [comment]
Yeah - could easily be considered a bug as well - I tagged it with "enhancement", not to indicate that that it wasn't a bug, but that it could be "low hanging fruit" for someone to tackle and resolve.

**Comment by benbp** [comment]
@brianparry @heckj Is this resolved or is there extra stuff? I'm noticing that there is a clear SEL graph that exists now: https://github.com/RackHD/on-taskgraph/blob/bc39102a17a2746b79405e5d394b271c79b72daf/lib/graphs/clear-sel-graph.js

**Comment by heckj** [comment]
Yeah, I kinda think it was resolved with https://github.com/RackHD/on-taskgraph/pull/10, @brianparry do you agree? Is there more that you were thinking about here that we should tackle?

**Comment by brianparry** [comment]
@benbp @heckj I think this covers the API initiated case.  We may eventually want to start this graph from the SEL poller though.

**Comment by heckj** [comment]
@brianparry thanks, I'll go ahead and close this issue then.
