### ISSUE TITLE
Services fail to start if RabbitMQ isn't available

### ISSUE THREAD

**Issue by kacole2** [RackHD/RackHD#59]
It would be nice if the services would retry to connect to RabbitMQ if it's not available instead of exiting completely.

this was tested with `on-dhcp-proxy`:
```
root@dmdev:/usr/src/on-dhcp-proxy# node index.js
Transmit Error getaddrinfo ENOTFOUND on-rabbitmq
```

**Comment by kacole2** [comment]
fixing this would be a big help in getting DHCP working with Docker.

**Comment by heckj** [comment]
@kacole2 I was digging into this code this afternoon, and there's reconnect mechanisms already in place, although apparently not working exactly as planning in your situation. 

It relies on an underlying amqp driver to do the reconnect work that I haven't started to debug (docs at https://www.npmjs.com/package/amqp#connection-options-and-url). Where there any tracebacks you had or anything else to help diagnose what wasn't happening here? Trying to sort out how to reproduce this in order to get it resolved.

**Comment by kacole2** [comment]
Easy to reproduce. 

Make sure Mongo is running and RabbitMQ is not. Then do "node start index.js" and it should fail for you

**Comment by heckj** [comment]
Thanks @kacole2, got it.

Working branch is `amqp-patience` in on-core, created a dummy app that exhibits exactly this behavior with manual integration testing. For what it's worth, I did use it to verify that once connected it will attempt (and successfully) reconnect if RabbitMQ "goes away" for a little while an then comes back.
