### ISSUE TITLE
Can not get the file "centos.ks" while install the CentOS.

### ISSUE THREAD

**Issue by Gary15** [RackHD/RackHD#68]
After help by @heckj in [issue#52](https://github.com/RackHD/RackHD/issues/52),I can use the RackHD server(VM) to accomplish the discovery tasks on the Dell R610.And I am trying to install the OS to Dell R610 by using `ipmi-obm-service`.Following the [ReadMe](https://github.com/RackHD/RackHD/blob/master/example/README.md),Installed a [default workflow](https://github.com/Gary15/WorkFlow/blob/master/dell_server_install_core.json) for Dell Server and a [SKUs](https://github.com/Gary15/WorkFlow/blob/master/dell_server_sku.json) definition.The installation of coreOS can be done.Then I try to install CentOS by post this [task](https://github.com/Gary15/WorkFlow/blob/master/ipmi_centos_iso_boot.json) to the node,the node can finish "set-pxe-boot" and "reboot", going to install the CentOS. Everything is ok untils transfer  the ks file to install the os automally. The [http 500 error](https://goo.gl/photos/V8tSrVbG1G6kDSjt9) coming out.And the node start [Dracut Emergency shell](https://goo.gl/photos/eUTfFrs9t7pbGp9r8).

**Comment by yyscamper** [comment]
Hi @Gary15:

The console should print out some detail information, I think you probably encountered the "cent-ks" rendering error.

After examining the JSON payload you passed to install centos workflow, you should miss the "version" field. In the InstallCentOS workflow definition (https://github.com/RackHD/on-taskgraph/blob/master/lib/graphs/install-centos-graph.js#L10) , the "version" is set as "null", it means you must specify an valid version number, otherwise the workflow will fail.

Below is a full example of install param I had created: https://gist.github.com/yyscamper/5a03ca228bb61aea8108

**Comment by yyscamper** [comment]
Per current design, only "version" is a must have option for install os workflow, even the "repo" is optional if you put the image in the default path "{{api.server}}/centos/{{options.version}}/os/x86_64". You could refer to the install-centos task definition for other default setting: https://github.com/RackHD/on-tasks/blob/master/lib/task-data/tasks/install-centos.js

**Comment by Gary15** [comment]
hi,@yyscamper Many thanks for answer. How can i attach the on-http/on-taskgraph console output on web? Or another place can get the log? Where can I refer to ? And I can not understand "rendering error" well.

---

I just run this pyhton file([setup_iso.py](https://github.com/RackHD/on-http/blob/master/data/templates/setup_iso.py)) to put the image to the server.

**Comment by yyscamper** [comment]
@Gary15:
The log should be under folder /var/log/upstart, you need sudo right to open the log file and use "less -R" to print the color code.

For rendering error, as the centos-ks is a template, it need be filled with some missing options to produce a valid kickstart file. This operation called "render", if some options miss, it will cause "rendering error".

Anyway, please first try whether it is due to missing "version" filed.

**Comment by Gary15** [comment]
@yyscamper Thanks ,very much. After I define the json file like this https://github.com/Gary15/WorkFlow/blob/master/ipmi_centos_iso_boot.json .The same error came out. Can not get the ks-file.

**Comment by Gary15** [comment]
You are right, It would be rendering error. I am trying to change the ks file location define in [install-centos.ipxe](https://github.com/RackHD/on-http/blob/master/data/profiles/install-centos.ipxe)  .It can go to install the OS but can not get the finished status.So it also failed by time out.
And I can't find useful log under folder [/var/log/upstart ](https://goo.gl/photos/jSrpyzm2NyeQbcxn9). Would you tell me to find out?

**Comment by yyscamper** [comment]
@Gary15 : I didn't have a chance to try the vagrant deploy, so there should be some difference between the vagrant environment and mine.

Please check this PR (https://github.com/RackHD/RackHD/pull/66/files), it redirects the log to /tmp folder. Please attach those logs for further analysis (Primary http.log and taskgraph.log)

**Comment by Gary15** [comment]
@yyscamper Sorry for delay so long, Here is the log info ([http.log](https://github.com/Gary15/WorkFlow/blob/master/http.log),[taskgraph.log](https://github.com/Gary15/WorkFlow/blob/master/taskgraph.log)),You can see the root cause is "driveId is not defined" while rendering the ks file from http.log. Could you give some advise for this?

**Comment by yyscamper** [comment]
Hi @Gary15 : your on-taskgraph service and on-http don't will match, we did change the name of "driveId" in kickstart file to "installDisk". Now your taskgraph log shows "installDisk" (https://github.com/Gary15/WorkFlow/blob/master/taskgraph.log#L167), but http log shows it tried to lookup driveId. 

The solution is to sync up all RackHD services, either all to latest or a specified but same branch (like 1.0.x branch is relative stable for CentOS/RHEL/ESXi installation and the 1.1.x branch is also more stable than master).

**Comment by Gary15** [comment]
Many thanks for your help, @yyscamper. It could be solved now.
