### ISSUE TITLE
No API to delete or edit Workflows

### ISSUE THREAD

**Issue by kacole2** [RackHD/RackHD#95]
I'm trying to create a workflow for my specific task but have noticed that I need to edit or change it through a series of trial and error until it runs correctly. 

There is no API to call a delete function on a workflow to remove it so it can be re-uploaded. In the same fashion, there is no call to PUT on a certain :id to allow manipulation of that ID. 

This is requiring me kill the vagrant environment and start over.

In addition, I cannot PUT a new Workflow with a different injectable and friendly name if it has most of the same parameters as the existing one.

**Comment by heckj** [comment]
@brianparry ^^ are you tracking for any specific APIs to help with this in the V2 API work you're doing?

**Comment by benbp** [comment]
@kacole2 as a workaround until the API has the functionality you need, you could just edit the files in `on-taskgraph/lib/graphs` and restart on-taskgraph, OR directly change them in mongo `mongo pxe; db.graphdefinitions.remove({injectableName: <workflowName>})` instead of killing the whole environment (much faster turnaround this way).

**Comment by brianparry** [comment]
@kacole2 @heckj I think this https://github.com/RackHD/on-http/pull/194 will cover most of what your looking for.  The 2.0 API separates workflows and graphs (definitions) into two sets of routes.  I think PUT and DELETE /workflows/graphs will do what you want.  We've also added support for DELETE /workflows/:id, so that old workflows can be deleted from the history.

**Comment by kacole2** [comment]
@brianparry nice! thanks!

**Comment by benbp** [comment]
@kacole2 I marked that PR as resolving this issue, assuming you agree with that.
